### PR TITLE
ISLANDORA-1825

### PR DESCRIPTION
**Pull request by uconnjeustis**
**JIRA Ticket**: (link)
[https://jira.duraspace.org/projects/ISLANDORA/issues/ISLANDORA-1825](https://jira.duraspace.org/projects/ISLANDORA/issues/ISLANDORA-1825)

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)
[Islandora Metadata Interest Group Notes on adding dateIssued](https://github.com/islandora-interest-groups/Islandora-Metadata-Interest-Group/blob/master/Meetings/12_12_2016.md)

# What does this Pull Request do?
The islandora_large_image_form_mods.xml includes the dateIssued field. This form would replace the existing default MODS XML form that doesn't have a dateIssued.

A brief description of what the intended result of the PR will be and/or what problem it solves.
All other default MODS xml forms have a dateIssued with the exception of the PDF and large image solution packs. This change will make the PDF default MODS xml form more consistent with other forms. It will also allow for more options beyond just dateCreated for users.

# What's new?
Added dateIssued in the default MODS xml form.

# How should this be tested?
This was tested locally in the XML form builder. The result from the preview was copied to Oxygen to ensure that the mods xml was valid.

A description of what steps someone could take to:
* Download this MODS xml form
* Import this form in their site and associate it to the Islandora PDF content model
* Ingest a PDF using this default form to see that the dateIssued appears

# Additional Notes:
This change doesn't require any change in documentation, any change to dependencies, modifications to other code. MODS xml file is on JIRA.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@uconnjeustis doing some pull reviews for our next release and found this one, but seems like your pull request is changing just the version to 1.8? Maybe you made a pull from an another branch by mistake. 
Please let me know if you still want the fix described in the pull message into release (code freeze march 1st), and if so, please update this pull, or close this and make a new one. Thanks a lot!

**Comment by uconnjeustis** [comment]
I had to remember what this was. Some time ago, the dev-ops asked to add
dateIssued to the XML MODS default forms in large image and PDF. I wasn't
able to add that so I attached a version of the XML MODS form with the
dateIssued in it in the jira ticket. I wasn't able to update the pull or
even attach the mods xml form in github.


I'm not sure what the final decision was from the dev-ops group. I didn't
know if they wanted to insert the dateIssued in the default MODS xml form
themselves or are fine just putting in the updated xml form into the
solution pack.

The only thing I did was added the dateIssued to the default xml MODS form.
But I can't attach it to the github issue only the jira ticket.

Jennifer

**Comment by DiegoPino** [comment]
@uconnjeustis ok, no worries. Lets do the following: please close this pull request. I will then take the XML form from JIRA ticket and create a new pull request with same description you had. Will ask you tomorrow to make sure i'm pulling the correct changes and ask someone else  @manez or @whikloj  to merge to have this `dateissued` change in place for code freeze. Thanks !

**Comment by uconnjeustis** [comment]
Sorry again for the delay. I needed to take care of some family issues and
was travelling. I'll close it now.

**Comment by uconnjeustis** [comment]
Per Diego's request, I'm closing this.

**Pull request closed without merging**
