### PR TITLE
ISLANDORA-1416 Fix for bad JP2 derivs

### PR DESCRIPTION
**Pull request by abbistani**

### CODE REVIEW

**Comment by rosiel** [comment]
Could you test for mimetype instead? That would preserve the existing functionality in case someone does ingest multi-page tiffs.

**Comment by adam-vessey** [comment]
Not sure the MIME-type is the way to go... Makes us dependent on having the full name of the file to have it, right? Maybe use imagemagick identify (we have some [code which calls out to it](https://github.com/Islandora/islandora_solution_pack_large_image/blob/7.x/includes/utilities.inc#L45-L55) already) to grab whatever info we need? Actually... Might be able to grab the MIME-type that way, if desired (to avoid making sure the extension is intact for our usual method of MIME-type detection)... Shrug?

**Comment by abbistani** [comment]
Even better, there's `islandora_large_image_is_tiff($file)` : https://github.com/abbistani/islandora_solution_pack_large_image/blob/ISLANDORA-1416/includes/derivatives.inc#L487-L497

If TIFF add the [0] else just use the filename?

**Comment by abbistani** [comment]
Yes.  I'm traveling  right now, but will try to have a revised PR in the next couple of days.

On 9/28/15, 7:01 PM, "Nick Ruest" <notifications@github.com<mailto:notifications@github.com>> wrote:

@abbistanihttps://github.com/abbistani checking back in - are you ok to proceed on this? We still have some time to get this in and tested for the release.

**Comment by abbistani** [comment]
I might test with a "problem" JP2.  The JP2 version of this map http://www.loc.gov/resource/g3861e.cw0013200/ is the one that produced the lovely examples in my JIRA ticket.

**Comment by rosiel** [comment]
Tested! Works with various images including the problematic one. Thumbs up to merge.

**Pull request merged**
