### PR TITLE
ISLANDORA-2306 Delete all this module's variables.

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2306

# What does this Pull Request do?

Causes the "Reset" button on the admin form, and the uninstall hook, to clean up all variables. 

# How should this be tested?

Try to reset saved values to their defaults with the reset button in the Large Images admin form - other than the viewer, it won't work. 

Same with uninstalling the module. 

With this PR, they should be removed.

# Additional Notes:

* Does this change require documentation to be updated?  No
* Does this change add any new dependencies? No
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No
* Could this change impact execution of existing code? 
**These variables are named generically - possibly a hangover from 6x, but they might be used elsewhere in other modules. They don't appear to be anywhere else in the Vagrant install, though. 

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by bryjbrown** [comment]
@rosiel It looks like this passed all the Travis CI tests, but for some reason GitHub thinks that the test is still pending. Do you know of a way we can have it run through the tests again?

**Comment by manez** [comment]
@bryjbrown I restarted the tests. Let's see if turning it off and turning it back on again works.

**Review by bryjbrown — APPROVED** [review]
Looks good to me.

**Comment by bryjbrown** [comment]
@rosiel Just fired this up in a VM and tested with resetting and uninstalling using 7.x and this PM. Sure enough, 7.x didn't clean up after itself and this PR does. Works as advertised, will merge in 24 if no one has an issue.

**Comment by rosiel** [comment]
thanks @bryjbrown!

**Pull request merged**
