### PR TITLE
ISLANDORA-2103 - Make sure thumbnails are in the RGB colorspace

### PR DESCRIPTION
**Pull request by jonathangreen**
## JIRA Ticket

https://jira.duraspace.org/browse/ISLANDORA-2103

## What does this Pull Request do?

If a CMYK image is uploaded to the large image solution pack, the thumbnail that we produce will not be viewable in IE/Edge since it can't display jpeg with a CMKY color space. 

## What's new? 

Update the derivative generation function to make sure the thumbnail is in RGB color space. Should work the same as before if the image was already RGB.

## How should this be tested?

Upload a source image that is CMYK, for example this image:
[CMYK TIFF.zip](https://github.com/Islandora/islandora_solution_pack_large_image/files/1428234/CMYK.TIFF.zip)

Thumbnail generated before this patch shouldn't be viewable in IE/Edge

## Interested parties
@ajstanley @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@jonathangreen ok, this makes sense and personally i feel having a CMYK thumbnail makes little sense. Does this work if the source has no profile at all? I saw this here some time ago  https://www.imagemagick.org/discourse-server/viewtopic.php?t=16464 and http://imagemagick.org/discourse-server/viewtopic.php?t=18844 but not sure if it applies on current version?

**Comment by jonathangreen** [comment]
@DiegoPino we are using this command to make sure things are in a RGB colorspace two other places in Islandora currently: 
https://github.com/Islandora/islandora_solution_pack_pdf/blob/7.x/includes/derivatives.inc#L333
https://github.com/Islandora/islandora_scholar/blob/7.x/includes/derivatives.inc#L269

It handles the files I've thrown at it, but as always it might not handle absolutely everything. The two forum threads you pointed to have a lot of information, but no real conclusions about what the best thing to do is. Do you have any files that you are specifically worried about?

**Comment by DiegoPino** [comment]
@jonathangreen files without a profile v/s with profile embedded, that are actually CMKY. In one of the cases, the transformation did not happen at all, in another one the resulting RGB was weird. For the sake of consistency, it is OK to keep on doing it like we did and my results are edge cases for sure. I will (if time allows me) do some extra tests and check back if i actually have a solution. If the results vary I will eventually make the other pulls and fixit.  Will approve and merge 24hrs after once this stuff passes. Thanks

**Review by DiegoPino — APPROVED** [review]

**Comment by DiegoPino** [comment]
24 hours passed. Merging

**Comment by bondjimbond** [comment]
@jonathangreen @DiegoPino Does this same issue apply to other cmodels? i.e. PDF, Newspaper, Book?

**Comment by jonathangreen** [comment]
@bondjimbond its actually books I'm having trouble with. All the image ones (book, newspaper) call out to this function to make thumbnails. The PDF SP makes its own thumbnails, but it already specifies this option.

**Comment by DiegoPino** [comment]
@jonathangreen @bondjimbond i can confirm that it could be an issue in webarchive and diskimage (but also less likely the source is actually CMKY on thise cases) But a search for  "200 x 200" should lead to all other modules that do this?

**Pull request merged**
