### PR TITLE
Remove errant space from jp2:ilyrrates parameters

### PR DESCRIPTION
**Pull request by Rarian**
The list of parameters specified for jp2:ilyrrates include an errant
space causing ImageMagick to believe the parameters after the space are
a filename to process causing an error:

```
2016-01-20T16:26:48-05:00 0:00.000 0.000u 6.7.7 Configure
convert[23699]: utility.c/ExpandFilenames/939/Configure
Command line: /usr/bin/convert {-debug} {All}
{/tmp/FILENAME.tif[0]} {-define} {numrlvls=6} {-define}
{jp2:tilewidth=1024} {-define} {jp2:tileheight=1024} {-define}
{jp2:rate=1.0} {-define} {jp2:lazy} {-define} {jp2:prg=rlcp} {-define}
{jp2:ilyrrates=0.015
625,0.01858,0.0221,0.025,0.03125,0.03716,0.04419,0.05,0.0625,}
{0.075,0.088,0.1,0.125,0.15,0.18,0.21,0.25,0.3,0.35,0.4,0.5,0.6,0.7,0.84}
{-define} {jp2:mode=int} {/tmp/FILENAME_JP2.jp2}
...
2016-01-20T16:26:48-05:00 0:00.300 0.290u 6.7.7 Exception
convert[23699]: blob.c/OpenBlob/2638/Exception
  unable to open image
`0.075,0.088,0.1,0.125,0.15,0.18,0.21,0.25,0.3,0.35,0.4,0.5,0.6,0.7,0.84':
No such file or directory
```

Resolves ISLANDORA-1584

### CODE REVIEW

**Comment by Rarian** [comment]
CLA submitted.

**Comment by manez** [comment]
@Rarian is iCLA'd up and ready to go!

**Comment by qadan** [comment]
Hey, nice catch! Looks like maybe a bad copypasta thing from the ImageMagick convert JP2 docs back in the day when Kakadu/ImageMagick toggle-ability was added? I'd be happy to merge this if we're cool with it, but it looks pretty cut-and-dry

**Comment by qadan** [comment]
Well, I've tested it, and there's just no way it's going to explode things, so moiged

**Comment by qadan** [comment]
I should probably start JIRA-ing. I'll be just a minute

**Pull request merged**
