### PR TITLE
add support for imagemagick with graphicsMagick

### PR DESCRIPTION
**Pull request by steverweber**
these two commits clean up code and add support for gm.  graphicsMagick is a fork of imagemagick with improved performance.

After completing this fix I was able to ingest 400mb tif without issues.

to use/test graphicsMagick support
apt-get install graphicsmagick-imagemagick-compat
in module ImageMagick change convert path to /usr/bin/gm and check graphicsMagick support.

### CODE REVIEW

**Comment by steverweber** [comment]
please review / pull

**Comment by steverweber** [comment]
also need to patch:
islandora_large_image.install

remove forced requirement of kdu_compress

> function islandora_large_image_requirements...

**Comment by steverweber** [comment]
kdu_compress is not opensource.
I run https://github.com/ksclarke/freelib-djatoka on a different server.
GraphicsMagick was successful with a 400mb tiff where kdu failed... not sure why... im using old 7year servers limited ram.

I never checked the performance... was happy with GM.

**Comment by ksclarke** [comment]
fwiw, freelib-djatoka uses kdu_compress... it's just packaged in the server. One of the goals of the project was to make djatoka much easier to use so it bundles everything in an easy to install package.  I will eventually switch the project to using openjpeg (removing the kakadu requirement), but I'm not there yet.

Of course if you're just using freelib-djatoka to serve, and not compress the images, you're not using kdu_compress, but you're still using kdu_expand.  Anyway, it does seem like, with there being a GM option, that kakadu shouldn't be _required_.  But, I'm just tuning in halfway through this discussion so I may have missed some context.

**Comment by willtp87** [comment]
Closing @ksclark has expressed interest in opening up a replacement for further iteration.

**Pull request closed without merging**
